version: "3.9"
services:
  postgres-db:
    image: postgres:15
    container_name: projectcanary-db
    environment:
      POSTGRES_USER: project_canary_takehome
      POSTGRES_PASSWORD: giveemissionsthebird
      POSTGRES_DB: project_canary_takehome
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: robalex@gmail.com
      PGADMIN_DEFAULT_PASSWORD: catsarecool
    ports:
      - "5050:80"
    depends_on:
      - postgres-db

volumes:
  db_data:
